apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: wanderlust
  labels:
    app: redis
spec:
  serviceName: "redis-service"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
              name: redis
          command:
            - redis-server
            - "--appendonly"
            - "yes" 
          volumeMounts:
            - name: redis-storage
              mountPath: /data  
      nodeSelector:
        workload-type: database
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "database"
          effect: "NoSchedule"
  volumeClaimTemplates:
    - metadata:
        name: redis-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "gp2"  
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: wanderlust
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  clusterIP: None 
